---
title: "Assignment 1 and 2"
output:
  html_document:
    df_print: paged
---

```{r, include = FALSE}
library(rio)
library(lubridate)
library(tidyverse)



  
link <- "https://github.com/MPA-Data-Viz/A1/raw/main/Burke.csv"

burke<-import(link)
```

```{r, include = FALSE}
burke$Date<-mdy(burke$Date)

burke <- burke %>% replace(is.na(.), 0)
```



```{r, include=FALSE}
burke_sum<-burke%>%group_by(Date)%>%
  summarise(Total = sum(`BGT North of NE 70th Total`),
            Ped_south = sum(`Ped South`),
            Ped_north = sum(`Ped North`),
            Bike_south = sum(`Bike South`),
            Bike_north = sum(`Bike North`))

burke_sum<-burke_sum%>%mutate(month = month(Date),
                      year = year(Date),
                      ped_total = Ped_south + Ped_north,
                      bike_total = Bike_south + Bike_north)

burke_sum<-burke_sum%>%filter(year %in% c(2014,2015,2016,2017))

burke_sum<-burke_sum%>%mutate(month = case_when(month == 1 ~ "Jan",
                                        month == 2 ~ "Feb",
                                        month == 3 ~ "Mar",
                                        month == 4 ~ "Apr",
                                        month == 5 ~ "May",
                                        month == 6 ~ "Jun",
                                        month == 7 ~ "Jul",
                                        month == 8 ~ "Aug",
                                        month == 9 ~ "Sep",
                                        month == 10 ~ "Oct",
                                        month == 11 ~ "Nov",
                                        month == 12 ~ "Dec"))


statVal<-summary(burke_sum$Total, digits = 3)
statVal<-statVal%>%as.vector()
upper<-((statVal[5]-statVal[2])*1.5)+statVal[5]

burke_sum_filt<-burke_sum%>%filter(Total <= upper)


burke_table<-burke_sum_filt%>%group_by(month)%>%
  summarise(total = sum(Total, na.rm = TRUE))


burke_table<-burke_table%>%mutate(percent = round(total / sum(total),2))

burke_table$month<-factor(burke_table$month, levels = c('Jan', 'Feb', 'Mar','Apr', 'May', 'Jun',
                                                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))


summer<-burke_table%>%filter(month %in% c('May', 'Jun', 'Jul', 'Aug'))
summer_total<-sum(summer$percent)*100
max_label<-max(burke_table$percent)*100

```


The Burke Gilman Trail in Seattle starts at Golden Gardens in the west, follows the ship canal to Lake Washington, and winds north along the lake until it ends in Bothell. The City of Seattle has been collecting data on the use of the trail since 2014. The below graphs show when and how the trail is primarily used.
<br>
<br>

```{r, echo = FALSE, warning=FALSE,message=FALSE}
ggplot(burke_table)+
  geom_bar(aes(month,percent), stat = 'identity', fill = "lightgreen")+
  labs(title = "Use of the Burke Gilman Trail Peaks in July",
       subtitle =paste0(summer_total,"% of Yearly Use Occurs May-Aug") ,
       x = NULL,
       y = NULL,
       caption = "Data collected at NE 70th St; 2014-2017 
Data from data.seattle.gov")+ 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1))+
  #geom_text(aes(month,percent,label = if_else(burke_table$month == "Jul", paste0(max_label,"%"), "")),
          #  position = position_dodge(width = .9), vjust = 0)+
  theme_minimal()
```



<br>
<br>
<br>
<br>



```{r, include = FALSE}
ped_avg<-round(mean(burke_sum_filt$ped_total),0)
bike_avg<-round(mean(burke_sum_filt$bike_total),0)

```



```{r, echo = FALSE, warning = FALSE, message=FALSE}
ggplot(burke_sum_filt)+
  geom_point(aes(ped_total,bike_total))+
  labs(title = "The Burke Gilman Trail sees more Bikes than Pedestrians per Day",
       subtitle = "1 Dot = 1 Day", 
       caption = "Data collected at NE 70th St; 2014-2017 
Data from data.seattle.gov",
        x = 'Total Pedestrians',
        y = 'Total Bikes')+
  theme_minimal()+
  geom_vline(xintercept = ped_avg, linetype= "dashed", color = "red")+
  geom_hline(yintercept = bike_avg, linetype = "dashed", color = "red")+
  annotate(geom = 'label', label = paste0("Average bikes per day: ",bike_avg,"
","Average pedestrians per day: ",ped_avg), 
            x = 2500, y = 3000, size = 4, hjust = .5, color = "red")
  


```

<br>
<br>
<br>
<br>
<br>

```{r, include = FALSE}

burke_sumDi<-burke_sum_filt%>%group_by(month)%>%
  summarise(Bike_south = mean(Bike_south),
            Bike_north = mean(Bike_north),
            Ped_south = mean(Ped_south),
            Ped_north = mean(Ped_north))

burke_sumDi$month<-factor(burke_sumDi$month, levels = c('Jan', 'Feb', 'Mar','Apr', 'May', 'Jun',
                                                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'))

burke_pivot<-burke_sumDi%>%pivot_longer(cols = c(Ped_south, Ped_north, Bike_south,Bike_north),
                                                      names_to = 'type',
                                                      values_to = 'Value')

burke_pivot<-burke_pivot%>%mutate(mode = if_else(grepl("Bike", type,), "Bike", "Pedestrian"))
burke_pivot<-burke_pivot%>%mutate(Direction = if_else(grepl("south", type,), "Southbound", "Northbound"))

```

```{r,echo = FALSE, warning = FALSE, message=FALSE}
ggplot(data = burke_pivot)+
  geom_point(aes(x = month, y = Value, color = Direction), shape = 5)+
  geom_segment(aes(x = month, y = 0, 
                   yend = Value,
                   xend = month), color = 'gray', size = .2)+
  labs(title = "Pedestrian Use of the Trail is Less Variable Across the Year Than Bike Usage",
       x = "Month",
       y = "Average Count",
       caption = "Data collected at NE 70th St; 2014-2017 
Data from data.seattle.gov")+
  facet_grid(~mode) + coord_flip()+
  scale_x_discrete(limits = rev(levels(burke_pivot$month)))+
  theme_minimal()
```


```{r}
burke_pivot<-burke_pivot%>%mutate(pyr_Value = if_else(Direction == "Southbound", -Value, Value))

pop_range <- range(burke_pivot$pyr_Value)
pretty(pop_range)
pop_range_breaks <- pretty(pop_range, n = 4)

```



```{r}
ggplot(data = burke_pivot)+
  geom_point(aes(x = month, y = pyr_Value, color = Direction), shape = 5, size = 2)+
  geom_segment(aes(x = month, y = 0, 
                   yend = pyr_Value,
                   xend = month, 
                   size = Value, 
                   color = Direction))+
  labs(title = "Pedestrian Use of the Trail is Less Variable Across the Year Than Bike Usage",
       x = "Month",
       y = "Average Count",
       caption = "Data collected at NE 70th St; 2014-2017 
Data from data.seattle.gov")+
  facet_grid(~mode) +
  scale_y_continuous(breaks  = pop_range_breaks,
                       labels = abs(pop_range_breaks))+ 
  theme_minimal()+
  theme(axis.text.x = element_text(angle=90, hjust=1))+
  guides(size = "none")



```

